CREATE OR REPLACE PROCEDURE getCustomers
IS
 cust SYS_REFCURSOR;
BEGIN
 Open cust for
 SELECT CUST_NAME, GRADE FROM customer WHERE OPENING_AMT + RECEIVE_AMT > 10000;
 DBMS_SQL.RETURN_RESULT(cust);
END;